name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and deploy
        run: |
          npm install
          git config --global user.email "nikolaidokken@live.no"
          git config --global user.name "Nikolai Dokken"
          npm run deploy
